FILE NAME: GEOGRAPHY_DIM_P00.SQL
--
-- DESCRIPTION:  THE SCRIPT HAS BEEN CREATED TO INSERT/UPDATE DATA INTO GEOGRAPHY_DIM 
-- AUTHOR(S):
-- 
--
-- LATEST REVISION:
-- 20210518 DRAFT CODE
---------------------------- 
	
-----------------------------------UPDATE GEOGRAPHY_DIM FILE SQL-------------------------------------------
UPDATE %TOBI_MDM%.GEOGRAPHY_DIM --DB NAME TO BE PICKED FROM PYTHON PARAMETER
FROM(
SELECT 
	GEOGRAPHY_DIM.PK_GEOGRAPHY_DIM_ID,
	STG_DIM_GEOGRAPHY_CHANGES.FK_TERRITORY_DIM_ID, 
	STG_DIM_GEOGRAPHY_CHANGES.REGION,     
	STG_DIM_GEOGRAPHY_CHANGES.SUB_REGION,  
	STG_DIM_GEOGRAPHY_CHANGES.COUNTRY, 
	STG_DIM_GEOGRAPHY_CHANGES.TERRITORY,  
	STG_DIM_GEOGRAPHY_CHANGES.STATE, 
	STG_DIM_GEOGRAPHY_CHANGES.COUNTY, 
	STG_DIM_GEOGRAPHY_CHANGES.CITY_CODE, 	
	STG_DIM_GEOGRAPHY_CHANGES.CITY, 
	STG_DIM_GEOGRAPHY_CHANGES.POPULATION, 
	STG_DIM_GEOGRAPHY_CHANGES.CITY_CATEGORY, 
	STG_DIM_GEOGRAPHY_CHANGES.DEPOT,  
	STG_DIM_GEOGRAPHY_CHANGES.BRANCH,   
    STG_DIM_GEOGRAPHY_CHANGES.KEY_CITY,   
    STG_DIM_GEOGRAPHY_CHANGES.TV_MARKET,   
	CAST(CAST(CURRENT_TIMESTAMP AS CHAR(19)) AS TIMESTAMP(0)) AS CREATED_DT,
	CAST(CAST(CURRENT_TIMESTAMP AS CHAR(19)) AS TIMESTAMP(0)) AS UPDATE_DT,
	CASE WHEN STG_DIM_GEOGRAPHY_CHANGES.DELETION_INDICATOR = 1 THEN 'Y' ELSE NULL END AS DELETED_FROM_MACCS,
	STG_DIM_GEOGRAPHY_CHANGES.DIVISION,   
    STG_DIM_GEOGRAPHY_CHANGES.AREA,   
    STG_DIM_GEOGRAPHY_CHANGES.CODE_LOCAL,   
    STG_DIM_GEOGRAPHY_CHANGES.BRANCH_SHORT_NM,  
	STG_DIM_GEOGRAPHY_CHANGES.DIVISION_SHORT_NM,
	STG_DIM_GEOGRAPHY_CHANGES.CITY_TAX_DESCRIPTION,  
	STG_DIM_GEOGRAPHY_CHANGES.FTPIX_LOCATION_CODE
	FROM %TOBI_STG%.STG_DIM_GEOGRAPHY_CHANGES STG_DIM_GEOGRAPHY_CHANGES
	LEFT JOIN $%TOBI_MDM%.GEOGRAPHY_DIM GEOGRAPHY_DIM ON(GEOGRAPHY_DIM.FK_TERRITORY_DIM_ID=STG_DIM_GEOGRAPHY_CHANGES.FK_TERRITORY_DIM_ID 
	AND GEOGRAPHY_DIM.CITY_CODE = STG_DIM_GEOGRAPHY_CHANGES.CITY_CODE
	AND GEOGRAPHY_DIM.COUNTRY= STG_DIM_GEOGRAPHY_CHANGES.COUNTRY)
	WHERE  GEOGRAPHY_DIM.PK_GEOGRAPHY_DIM_ID IS NOT NULL
	AND STG_DIM_GEOGRAPHY_CHANGES.FK_TERRITORY_DIM_ID
	IN (SELECT TERRITORY_ID
                FROM %TOBI_ADMIN%.FDDM_LOAD_TERRITORIES
                WHERE LOAD_STATUS = 'COMPLETED'
                      AND REGION_ID = (SELECT DISTINCT REGION_ID FROM %TOBI_ADMIN%.TOBI_CONFIG WHERE RUN_FLAG='Y')) --REGION_ID TO BE PICKED FROM PYTHON SCRIPT PARAMETER
)UPD_SET
SET
REGION=UPD_SET.REGION,		
SUB_REGION=UPD_SET.SUB_REGION, 		
COUNTRY=UPD_SET.COUNTRY,						
TERRITORY=UPD_SET.TERRITORY,			
STATE=UPD_SET.STATE,				
UPDATE_DT=UPD_SET.UPDATE_DT,			
DELETED_FROM_MACCS=UPD_SET.DELETED_FROM_MACCS,	
CITY_CODE=UPD_SET.CITY_CODE	,
COUNTY=UPD_SET.COUNTY,
CITY=UPD_SET.CITY,
POPULATION=UPD_SET.POPULATION,
CITY_CATEGORY=UPD_SET.CITY_CATEGORY,
DEPOT=UPD_SET.DEPOT,
BRANCH=UPD_SET.BRANCH,
KEY_CITY=UPD_SET.KEY_CITY,	
TV_MARKET=UPD_SET.TV_MARKET	,
DIVISION=UPD_SET.DIVISION,
AREA=UPD_SET.AREA,
CODE_LOCAL=UPD_SET.CODE_LOCAL,
BRANCH_SHORT_NM=UPD_SET.BRANCH_SHORT_NM,
DIVISION_SHORT_NM=UPD_SET.DIVISION_SHORT_NM,
CITY_TAX_DESCRIPTION=UPD_SET.CITY_TAX_DESCRIPTION,
FTPIX_LOCATION_CODE=UPD_SET.FTPIX_LOCATION_CODE	
WHERE GEOGRAPHY_DIM.PK_GEOGRAPHY_DIM_ID=UPD_SET.PK_GEOGRAPHY_DIM_ID
AND GEOGRAPHY_DIM.FK_TERRITORY_DIM_ID=UPD_SET.FK_TERRITORY_DIM_ID;


----------------------------------INSERT GEOGRAPHY_DIM SQL-------------------------------------------
INSERT INTO %TOBI_MDM%.GEOGRAPHY_DIM --DB NAME TO BE PICKED FROM PYTHON PARAMETER
(
PK_GEOGRAPHY_DIM_ID,
	  FK_TERRITORY_DIM_ID,
      REGION ,
      SUB_REGION ,
      COUNTRY ,
      TERRITORY ,
      STATE ,
     CITY_CODE ,
      COUNTY ,
      CITY ,
      POPULATION ,
      CITY_CATEGORY  ,
      DEPOT ,
      BRANCH ,
      KEY_CITY ,
      TV_MARKET ,
      CREATED_DT,
      UPDATE_DT,
      DELETED_FROM_MACCS,
      DIVISION ,
      AREA ,
      CODE_LOCAL ,
      BRANCH_SHORT_NM ,
      DIVISION_SHORT_NM ,
      CITY_TAX_DESCRIPTION ,
      FTPIX_LOCATION_CODE 
)
	SELECT 
	ROW_NUMBER()OVER(ORDER BY STG_DIM_GEOGRAPHY_CHANGES.FK_TERRITORY_DIM_ID,STG_DIM_GEOGRAPHY_CHANGES.CITY, STG_DIM_GEOGRAPHY_CHANGES.COUNTY) + ID_MX AS PK_GEOGRAPHY_DIM_ID,
	STG_DIM_GEOGRAPHY_CHANGES.FK_TERRITORY_DIM_ID, 
	STG_DIM_GEOGRAPHY_CHANGES.REGION,     
	STG_DIM_GEOGRAPHY_CHANGES.SUB_REGION,  
	STG_DIM_GEOGRAPHY_CHANGES.COUNTRY, 
	STG_DIM_GEOGRAPHY_CHANGES.TERRITORY,  
	STG_DIM_GEOGRAPHY_CHANGES.STATE, 
	STG_DIM_GEOGRAPHY_CHANGES.CITY_CODE, 	
    	STG_DIM_GEOGRAPHY_CHANGES.COUNTY, 
	STG_DIM_GEOGRAPHY_CHANGES.CITY, 
	STG_DIM_GEOGRAPHY_CHANGES.POPULATION, 
	STG_DIM_GEOGRAPHY_CHANGES.CITY_CATEGORY, 
	STG_DIM_GEOGRAPHY_CHANGES.DEPOT,  
	STG_DIM_GEOGRAPHY_CHANGES.BRANCH,   
    	STG_DIM_GEOGRAPHY_CHANGES.KEY_CITY,   
    	STG_DIM_GEOGRAPHY_CHANGES.TV_MARKET,   
	CAST(CAST(CURRENT_TIMESTAMP AS CHAR(19)) AS TIMESTAMP(0)) AS CREATED_DT,
	CAST(CAST(CURRENT_TIMESTAMP AS CHAR(19)) AS TIMESTAMP(0)) AS UPDATE_DT,
	CASE WHEN STG_DIM_GEOGRAPHY_CHANGES.DELETION_INDICATOR = 1 THEN 'Y' ELSE NULL END AS DELETED_FROM_MACCS,
	STG_DIM_GEOGRAPHY_CHANGES.DIVISION,   
   	STG_DIM_GEOGRAPHY_CHANGES.AREA,   
    	STG_DIM_GEOGRAPHY_CHANGES.CODE_LOCAL,   
    	STG_DIM_GEOGRAPHY_CHANGES.BRANCH_SHORT_NM,  
	STG_DIM_GEOGRAPHY_CHANGES.DIVISION_SHORT_NM,
	STG_DIM_GEOGRAPHY_CHANGES.CITY_TAX_DESCRIPTION,  
	STG_DIM_GEOGRAPHY_CHANGES.FTPIX_LOCATION_CODE
	FROM %TOBI_STG%.STG_DIM_GEOGRAPHY_CHANGES STG_DIM_GEOGRAPHY_CHANGES
	LEFT JOIN %TOBI_MDM%.GEOGRAPHY_DIM GEOGRAPHY_DIM ON(GEOGRAPHY_DIM.FK_TERRITORY_DIM_ID=STG_DIM_GEOGRAPHY_CHANGES.FK_TERRITORY_DIM_ID 
	AND GEOGRAPHY_DIM.CITY_CODE = STG_DIM_GEOGRAPHY_CHANGES.CITY_CODE
	AND GEOGRAPHY_DIM.COUNTRY= STG_DIM_GEOGRAPHY_CHANGES.COUNTRY)
	CROSS JOIN (SELECT MAX(PK_GEOGRAPHY_DIM_ID) AS ID_MX FROM %TOBI_MDM%.GEOGRAPHY_DIM) AS MX
	WHERE  GEOGRAPHY_DIM.PK_GEOGRAPHY_DIM_ID IS NULL
	AND STG_DIM_GEOGRAPHY_CHANGES.FK_TERRITORY_DIM_ID
	IN (SELECT TERRITORY_ID
                FROM %TOBI_ADMIN%.FDDM_LOAD_TERRITORIES
                WHERE LOAD_STATUS = 'COMPLETED'
                      AND REGION_ID = (SELECT DISTINCT REGION_ID FROM %TOBI_ADMIN%.TOBI_CONFIG WHERE RUN_FLAG='Y')) --REGION_ID TO BE PICKED FROM PYTHON SCRIPT PARAMETER


