/*FILE NAME: PRODUCT_DIM_P00.sql
--
-- DESCRIPTION:  THE SCRIPT HAS BEEN CREATED TO INSERT/UPDATE DATA INTO PRODUCT_DIM
-- AUTHOR(S):
-- 
--
-- LATEST REVISION:
-- 20210514 DRAFT CODE
----------------------------*/

/*-----------------------------------UPDATE PRODUCT_DIM FILE SQL-------------------------------------------*/

UPDATE %TOBI_MDM%.PRODUCT_DIM 
FROM(
SELECT 
PRODUCT_DIM.PK_PRODUCT_DIM_ID
, PRODUCT.TERRITORY_ID AS FK_TERRITORY_DIM_ID
, PRODUCT.CODE AS PRODUCT_CODE
, CAST(NULL AS VARCHAR(15)) AS PRODUCT_CATEGORY
, PRODUCT.DESCRIPTION AS PRODUCT_DESCRIPTION
,CAST(CAST(CURRENT_TIMESTAMP AS CHAR(19)) AS TIMESTAMP(0)) AS CREATED_DT
,CAST(CAST(CURRENT_TIMESTAMP AS CHAR(19)) AS TIMESTAMP(0)) AS UPDATE_DT
, PRODUCT.EXPIRED AS EXPIRED
, GCT_PRODUCT_TYPE.DESCRIPTION AS PRODUCT_TYPE
,CASE WHEN PRODUCT.DELETION_INDICATOR = 1 THEN 'Y' ELSE NULL END AS DELETED_FROM_MACCS 
,CASE WHEN TCT_PRODUCT_MAPPING.COMMON_PRODUCT IS NULL THEN 'OTHER_INVOICE_PRODUCT' ELSE TCT_PRODUCT_MAPPING.COMMON_PRODUCT END AS COMMON_PRODUCT
,1 AS CHANGED_FLAG
, PRODUCT.CONTRIBUTION_COLUMN AS CONTRIBUTION_FLAG
, PRODUCT.EXTRA_RENTAL_COLUMN AS EXTRA_RENTAL_FLAG
,PRODUCT.VAT_COLUMN AS VAT_COLUMN
, TITLE_DIM.PK_TITLE_DIM_ID AS FK_TITLE_DIM_ID
, TITLE_DIM.FK_DISTRIBUTOR_DIM_ID
,ACCOUNT_DIM.PK_ACCOUNT_DIM_ID AS FK_ACCOUNT_DIM_ID
FROM
 %TOBI_ODS%.PRODUCT PRODUCT
 LEFT OUTER JOIN FDDM_ODS.TCT_PRODUCT_MAPPING TCT_PRODUCT_MAPPING
 ON(PRODUCT.CODE=TCT_PRODUCT_MAPPING.CODE AND PRODUCT.TERRITORY_ID=TCT_PRODUCT_MAPPING.TERRITORY_ID)
LEFT OUTER JOIN %TOBI_ODS%.MASTER_TITLE MASTER_TITLE
 ON(PRODUCT.CODE_TITLE=MASTER_TITLE.CODE AND PRODUCT.TERRITORY_ID=MASTER_TITLE.TERRITORY_ID)
LEFT OUTER JOIN FDDM_ODS_DCX_DEV.GCT_PRODUCT_TYPE GCT_PRODUCT_TYPE ON 
(PRODUCT.CODE_PRODUCT_TYPE =GCT_PRODUCT_TYPE.CODE) 
LEFT OUTER JOIN %TOBI_MDM%.TITLE_DIM TITLE_DIM
ON(TITLE_DIM.TITLE_CD_NK=PRODUCT.CODE_TITLE AND TITLE_DIM.FK_TERRITORY_DIM_ID=PRODUCT.TERRITORY_ID)
LEFT OUTER JOIN %TOBI_MDM%.ACCOUNT_DIM ACCOUNT_DIM
ON(ACCOUNT_DIM.ACCOUNT_CD_NK=PRODUCT.CODE_ACCOUNT AND ACCOUNT_DIM.FK_TERRITORY_DIM_ID=PRODUCT.TERRITORY_ID)
LEFT OUTER JOIN %TOBI_MDM%.PRODUCT_DIM PRODUCT_DIM ON 
(PRODUCT_DIM.PRODUCT_CODE=PRODUCT.CODE AND PRODUCT_DIM.FK_TERRITORY_DIM_ID=PRODUCT.TERRITORY_ID)
WHERE
PRODUCT_DIM.PK_PRODUCT_DIM_ID IS NOT NULL AND 
 PRODUCT.TERRITORY_ID IN  (SELECT TERRITORY_ID
                FROM %TOBI_ADMIN%.FDDM_LOAD_TERRITORIES --DB NAME TO BE PICKED FROM PYTHON PARAMETER
                WHERE LOAD_STATUS = 'COMPLETED'
                      AND REGION_ID = (SELECT DISTINCT REGION_ID FROM %TOBI_ADMIN%.TOBI_CONFIG WHERE RUN_FLAG='Y'))
AND PRODUCT.DW_TIMESTAMP>(SELECT LOAD_START_DATE FROM %TOBI_ADMIN%.FDDM_MDM_LOAD_STATE 
WHERE REGION_ID=(SELECT DISTINCT REGION_ID FROM %TOBI_ADMIN%.TOBI_CONFIG WHERE RUN_FLAG='Y'))
)UPD_SET
SET
PRODUCT_CODE=UPD_SET.PRODUCT_CODE,		
PRODUCT_DESCRIPTION=UPD_SET.PRODUCT_DESCRIPTION, 		
EXPIRED=UPD_SET.EXPIRED,
PRODUCT_CATEGORY=UPD_SET.PRODUCT_CATEGORY,						
PRODUCT_TYPE=UPD_SET.PRODUCT_TYPE,			
COMMON_PRODUCT=UPD_SET.COMMON_PRODUCT,					
UPDATE_DT=UPD_SET.UPDATE_DT,			
DELETED_FROM_MACCS=UPD_SET.DELETED_FROM_MACCS,	
CONTRIBUTION_FLAG=UPD_SET.CONTRIBUTION_FLAG	,
EXTRA_RENTAL_FLAG=UPD_SET.EXTRA_RENTAL_FLAG,
VAT_COLUMN=UPD_SET.VAT_COLUMN,
FK_TITLE_DIM_ID=UPD_SET.FK_TITLE_DIM_ID,
FK_DISTRIBUTOR_DIM_ID=UPD_SET.FK_DISTRIBUTOR_DIM_ID,
FK_ACCOUNT_DIM_ID=UPD_SET.FK_ACCOUNT_DIM_ID
WHERE PRODUCT_DIM.PK_PRODUCT_DIM_ID=UPD_SET.PK_PRODUCT_DIM_ID
AND PRODUCT_DIM.FK_TERRITORY_DIM_ID=UPD_SET.FK_TERRITORY_DIM_ID;

/*----------------------------------INSERT PRODUCT_DIM SQL-------------------------------------------*/

INSERT INTO %TOBI_MDM%.PRODUCT_DIM 
(PK_PRODUCT_DIM_ID, 
FK_TERRITORY_DIM_ID, 
PRODUCT_CODE, 
PRODUCT_CATEGORY, 
PRODUCT_DESCRIPTION, 
CREATED_DT, 
UPDATE_DT, 
EXPIRED, 
PRODUCT_TYPE, 
DELETED_FROM_MACCS, 
COMMON_PRODUCT, 
CHANGED_FLAG, 
CONTRIBUTION_FLAG, 
EXTRA_RENTAL_FLAG, 
VAT_COLUMN, 
FK_TITLE_DIM_ID, 
FK_DISTRIBUTOR_DIM_ID, 
FK_ACCOUNT_DIM_ID
)
SELECT 
ROW_NUMBER()OVER(ORDER BY PRODUCT.TERRITORY_ID,PRODUCT.CODE) + ID_MX   AS  PK_PRODUCT_DIM_ID
, PRODUCT.TERRITORY_ID AS FK_TERRITORY_DIM_ID
, PRODUCT.CODE AS PRODUCT_CODE
, CAST(NULL AS VARCHAR(15)) AS PRODUCT_CATEGORY
, PRODUCT.DESCRIPTION AS PRODUCT_DESCRIPTION
,CAST(CAST(CURRENT_TIMESTAMP AS CHAR(19)) AS TIMESTAMP(0)) AS CREATED_DT
,CAST(CAST(CURRENT_TIMESTAMP AS CHAR(19)) AS TIMESTAMP(0)) AS UPDATE_DT
, PRODUCT.EXPIRED AS EXPIRED
, GCT_PRODUCT_TYPE.DESCRIPTION AS PRODUCT_TYPE
,NULL AS DELETED_FROM_MACCS 
,CASE WHEN TCT_PRODUCT_MAPPING.COMMON_PRODUCT IS NULL THEN 'OTHER_INVOICE_PRODUCT' ELSE TCT_PRODUCT_MAPPING.COMMON_PRODUCT END AS COMMON_PRODUCT
,1 AS CHANGED_FLAG
, PRODUCT.CONTRIBUTION_COLUMN AS CONTRIBUTION_FLAG
, PRODUCT.EXTRA_RENTAL_COLUMN AS EXTRA_RENTAL_FLAG
,PRODUCT.VAT_COLUMN AS VAT_COLUMN
, TITLE_DIM.PK_TITLE_DIM_ID AS FK_TITLE_DIM_ID
, TITLE_DIM.FK_DISTRIBUTOR_DIM_ID
,ACCOUNT_DIM.PK_ACCOUNT_DIM_ID AS FK_ACCOUNT_DIM_ID
FROM
 %TOBI_ODS%.PRODUCT PRODUCT
 LEFT OUTER JOIN FDDM_ODS.TCT_PRODUCT_MAPPING TCT_PRODUCT_MAPPING
 ON(PRODUCT.CODE=TCT_PRODUCT_MAPPING.CODE AND PRODUCT.TERRITORY_ID=TCT_PRODUCT_MAPPING.TERRITORY_ID)
LEFT OUTER JOIN %TOBI_ODS%.MASTER_TITLE MASTER_TITLE
 ON(PRODUCT.CODE_TITLE=MASTER_TITLE.CODE AND PRODUCT.TERRITORY_ID=MASTER_TITLE.TERRITORY_ID)
LEFT OUTER JOIN FDDM_ODS_DCX_DEV.GCT_PRODUCT_TYPE GCT_PRODUCT_TYPE ON 
(PRODUCT.CODE_PRODUCT_TYPE =GCT_PRODUCT_TYPE.CODE) 
LEFT OUTER JOIN %TOBI_MDM%.TITLE_DIM TITLE_DIM
ON(TITLE_DIM.TITLE_CD_NK=PRODUCT.CODE_TITLE AND TITLE_DIM.FK_TERRITORY_DIM_ID=PRODUCT.TERRITORY_ID)
LEFT OUTER JOIN %TOBI_MDM%.ACCOUNT_DIM ACCOUNT_DIM
ON(ACCOUNT_DIM.ACCOUNT_CD_NK=PRODUCT.CODE_ACCOUNT AND ACCOUNT_DIM.FK_TERRITORY_DIM_ID=PRODUCT.TERRITORY_ID)
LEFT OUTER JOIN %TOBI_MDM%.PRODUCT_DIM PRODUCT_DIM ON 
(PRODUCT_DIM.PRODUCT_CODE=PRODUCT.CODE AND PRODUCT_DIM.FK_TERRITORY_DIM_ID=PRODUCT.TERRITORY_ID)
CROSS JOIN (SELECT MAX(PK_PRODUCT_DIM_ID) AS ID_MX FROM %TOBI_MDM%.PRODUCT_DIM) AS MX
WHERE
PRODUCT_DIM.PK_PRODUCT_DIM_ID IS NULL AND 
 PRODUCT.TERRITORY_ID IN  (SELECT TERRITORY_ID
                FROM %TOBI_ADMIN%.FDDM_LOAD_TERRITORIES
                WHERE LOAD_STATUS = 'COMPLETED'
                      AND REGION_ID = (SELECT DISTINCT REGION_ID FROM %TOBI_ADMIN%.TOBI_CONFIG WHERE RUN_FLAG='Y'))
AND PRODUCT.DW_TIMESTAMP>(SELECT LOAD_START_DATE FROM %TOBI_ADMIN%.FDDM_MDM_LOAD_STATE 
WHERE REGION_ID=(SELECT DISTINCT REGION_ID FROM %TOBI_ADMIN%.TOBI_CONFIG WHERE RUN_FLAG='Y'));
