-----------------------------------ACCOUNTS_RECEIVABLE_FACT_P00.SQL-------------------------------------------------
/* 
#### COPYRIGHTS			: TBD
#### FILE NAME			: WBO_ACCOUNTS_RECEIVABLE_FCT_P00.SQL  
#### FILE TYPE			: SQL FILE
#### APPLICATION		: TOBI 
#### BUSINESS FUNCTION	: THIS FILE HAS BEEN CREATED TO PERFORM INSERT/UPDATE INTO ACCOUNTS_RECEIVABLE_FCT TABLE & 
####					  DELETE / INSERT TO TEMP TABLES.
#### AUTHOR(S)			: RAGHURAM NALADALA                                                                                       
####                    :   
#### VERSION			: 1-INITIAL VERSION 
#### DATE				: 20-SEP-2021 */ 

/* --------------------------------DELETE / INSERT TEMP_ACC_REV_PAYER SQL START --------------------------------------- */

DELETE %TOBI_MDM%.TEMP_ACC_REV_PAYER WHERE TERRITORY_ID IN 
(SELECT TERRITORY_ID FROM %TOBI_ADMIN%.TOBI_JOB_RUN_TERRITORY WHERE JOB_RUN_FLAG='Y' AND REGION_ID =(SELECT DISTINCT REGION_ID FROM %TOBI_ADMIN%.TOBI_JOB_SQL_FILE_PATH WHERE JOB_RUN_FLAG='Y'));

INSERT INTO %TOBI_MDM%.TEMP_ACC_REV_PAYER
(
TERRITORY_ID,
PAYER_DIM_ID,
ACC_REV_12MNTHS
)
SELECT
  PARTY_CINEMA_PAYER_DIM.FK_TERRITORY_DIM_ID,
  PARTY_CINEMA_PAYER_DIM.PK_PARTY_DIM_ID,
  NVL(SUM(INVOICE_PIVOT_FCT_MV.RENTAL_PRODUCTS),0) ACC_REV_12_MNTHS
FROM   
%TOBI_MDM%.PARTY_CINEMA_PAYER_DIM,
%TOBI_MDM%.INVOICE_FCT_MV 
left OUTER JOIN %TOBI_MDM%.INVOICE_PIVOT_FCT_MV on INVOICE_FCT_MV.PK_INVOICE_DIM_ID = INVOICE_PIVOT_FCT_MV.PK_INVOICE_DIM_ID
  and INVOICE_FCT_MV.PK_INVOICE_SUBCODE_NK=INVOICE_PIVOT_FCT_MV.PK_INVOICE_SUBCODE_NK
  and INVOICE_FCT_MV.PK_TERRITORY_DIM_ID=INVOICE_PIVOT_FCT_MV.PK_TERRITORY_DIM_ID
  and INVOICE_FCT_MV.PK_TERRITORY_DIM_ID=INVOICE_PIVOT_FCT_MV.PK_TERRITORY_DIM_ID,
%TOBI_MDM%.INVOICE_DIM,
%TOBI_MDM%.TIME_DIM
WHERE  ( PARTY_CINEMA_PAYER_DIM.PK_PARTY_DIM_ID=INVOICE_FCT_MV.FK_PARTY_CINEMA_PAYER
  AND  PARTY_CINEMA_PAYER_DIM.FK_TERRITORY_DIM_ID = INVOICE_FCT_MV.PK_TERRITORY_DIM_ID )
  AND  ( INVOICE_DIM.PK_INVOICE_DIM_ID=INVOICE_FCT_MV.PK_INVOICE_DIM_ID 
  AND    INVOICE_DIM.FK_TERRITORY_DIM_ID=INVOICE_FCT_MV.PK_TERRITORY_DIM_ID  )
  AND  ( PARTY_CINEMA_PAYER_DIM.DELETED_FROM_MACCS IS NULL  )---Payer is not deleted from MACCS
  AND  ( INVOICE_DIM.DELETED_FROM_MACCS IS NULL ) ----Invoice is not deleted from MACCS
  AND  TIME_DIM.PK_TIME_DIM_ID = INVOICE_FCT_MV.FK_TIME_INVOICE_DATE
  AND  TIME_DIM.FULL_DATE  BETWEEN  CURRENT_DATE - 365 AND CURRENT_DATE
  AND  PARTY_CINEMA_PAYER_DIM.FK_TERRITORY_DIM_ID IN 
  (SELECT TERRITORY_ID FROM %TOBI_ADMIN%.TOBI_JOB_RUN_TERRITORY WHERE JOB_RUN_FLAG='Y' AND REGION_ID =(SELECT DISTINCT REGION_ID FROM %TOBI_ADMIN%.TOBI_JOB_SQL_FILE_PATH WHERE JOB_RUN_FLAG='Y'))
  GROUP BY  PARTY_CINEMA_PAYER_DIM.FK_TERRITORY_DIM_ID,PARTY_CINEMA_PAYER_DIM.PK_PARTY_DIM_ID ;
   
/* --------------------------------DELETE / INSERT TEMP_ACC_REV_PAYER SQL END --------------------------------------- */

/* --------------------------------DELETE / INSERT TEMP_INVOICE_DATA_PAYER SQL START --------------------------------------- */

DELETE %TOBI_ODS%.TEMP_INVOICE_DATA_PAYER where TERRITORY_ID IN 
(SELECT TERRITORY_ID FROM %TOBI_ADMIN%.TOBI_JOB_RUN_TERRITORY WHERE JOB_RUN_FLAG='Y' AND REGION_ID =(SELECT DISTINCT REGION_ID FROM %TOBI_ADMIN%.TOBI_JOB_SQL_FILE_PATH WHERE JOB_RUN_FLAG='Y'));

INSERT INTO %TOBI_ODS%.TEMP_INVOICE_DATA_PAYER
(
TERRITORY_ID,
CODE_RELATION_PAYER,
INVOICE_AMT,
CASH_RECEIVED,
OPEN_AMT,
MISC_PAYMENTS,
AR_AMOUNT
)
SELECT
SUBQRY.TERRITORY_ID,
SUBQRY.CODE_RELATION_PAYER CODE_RELATION_PAYER,
--SUBQRY.CODE_CIRCUIT CODE_CIRCUIT,
SUM(SUBQRY.INVOICE_AMT) AS INVOICE_AMT,
SUM(SUBQRY.CASH_RECEIVED) AS CASH_RECEIVED,
SUM(SUBQRY.OPEN_AMT) AS OPEN_AMT,
SUM(SUBQRY.MISC_PAYM) AS MISC_PAYM,
SUM(SUBQRY.OPEN_AMT) - SUM(SUBQRY.MISC_PAYM) AS AR_AMT
FROM
 (
SELECT
 I.TERRITORY_ID TERRITORY_ID,
 I.CODE_RELATION_PAYER CODE_RELATION_PAYER,
 --I.CODE_CIRCUIT CODE_CIRCUIT,
 SUM(TOT_AMOUNT) AS INVOICE_AMT,
 SUM(RECEIVED_AMOUNT) AS CASH_RECEIVED,
 SUM(TOT_AMOUNT-RECEIVED_AMOUNT) AS OPEN_AMT,
 CAST(0 AS INTEGER) AS MISC_PAYM
 FROM %TOBI_ODS%.INVOICE I
     WHERE 
     I.INVOICE_STATUS ='f' AND I.DELETION_INDICATOR <> 1
group by  I.CODE_RELATION_PAYER,I.CODE_CIRCUIT, I.TERRITORY_ID
UNION
 SELECT
  P.TERRITORY_ID TERRITORY_ID,
  P.CODE_RELATION_PAYER CODE_RELATION_PAYER,
   CAST(0 AS INTEGER) AS INVOICE_AMT, CAST(0 AS INTEGER) AS CASH_RECEIVED, CAST(0 AS INTEGER) AS OPEN_AMT,
  SUM (BSSD.AMOUNT) AS MISC_PAYM
     FROM %TOBI_ODS%.BANK_STATEMENT BS,
          %TOBI_ODS%.BANK_STATEMENT_DETAIL BSD,
          %TOBI_ODS%.BANK_STATEMENT_SUBDETAIL BSSD,
          %TOBI_ODS%.MACCS_RELATION MRP,
          %TOBI_ODS%.PAYER P
    WHERE BS.code = BSD.code_bank_statement
      AND BSD.code_bank_statement = BSSD.code_bank_statement
      AND BSD.subcode = BSSD.subcode
      AND BSD.code_relation_payer = MRP.code
      AND BSD.code_relation_payer = P.code_relation_payer
      AND BSSD.code_misc_invoice IS NOT NULL
   AND BS.statement_status = 'a'
      AND BSD.value_date BETWEEN CAST(CAST('1950-01-01' AS DATE) AS DATE FORMAT 'DD/MM/YYYY')  AND CAST(CAST('2050-01-01' AS DATE) AS DATE FORMAT 'DD/MM/YYYY') 
      AND (BS.TERRITORY_ID = BSD.TERRITORY_ID AND
           BSD.TERRITORY_ID = BSSD.TERRITORY_ID AND
           BSSD.TERRITORY_ID = MRP.TERRITORY_ID AND
           MRP.TERRITORY_ID = P.TERRITORY_ID
AND (COALESCE(BS.DELETION_INDICATOR,'0') <> 1)
           )
      group by  P.CODE_RELATION_PAYER, P.TERRITORY_ID
   HAVING SUM (BSSD.amount) <> 0
) SUBQRY
WHERE SUBQRY.TERRITORY_ID IN 
(SELECT TERRITORY_ID FROM %TOBI_ADMIN%.TOBI_JOB_RUN_TERRITORY WHERE JOB_RUN_FLAG='Y' AND REGION_ID =(SELECT DISTINCT REGION_ID FROM %TOBI_ADMIN%.TOBI_JOB_SQL_FILE_PATH WHERE JOB_RUN_FLAG='Y'))
GROUP BY  SUBQRY.CODE_RELATION_PAYER,SUBQRY.TERRITORY_ID
HAVING (SUM(SUBQRY.OPEN_AMT) - SUM(SUBQRY.MISC_PAYM)) > 0 ;

/* --------------------------------DELETE / INSERT TEMP_INVOICE_DATA_PAYER SQL END --------------------------------------- */

/* --------------------------------DELETE / INSERT TEMP_WBO_DATA_PAYER SQL START --------------------------------------- */

DELETE %TOBI_ODS%.TEMP_WBO_DATA_PAYER WHERE TERRITORY_ID IN 
(SELECT TERRITORY_ID FROM %TOBI_ADMIN%.TOBI_JOB_RUN_TERRITORY WHERE JOB_RUN_FLAG='Y' AND REGION_ID =(SELECT DISTINCT REGION_ID FROM %TOBI_ADMIN%.TOBI_JOB_SQL_FILE_PATH WHERE JOB_RUN_FLAG='Y'));

INSERT INTO %TOBI_ODS%.TEMP_WBO_DATA_PAYER
(
TERRITORY_ID,
CODE_RELATION_PAYER,
BILLING_AMT,
CUM_BILLING_AMT,
DAYNUM,
BILLING_DATE
)
SELECT
SUBQRY1.TERRITORY_ID,
SUBQRY1.CODE_RELATION_PAYER,
SUBQRY1.BILLING_AMT BILLING_AMT,
SUM(SUBQRY1.BILLING_AMT) OVER (PARTITION BY SUBQRY1.TERRITORY_ID,SUBQRY1.CODE_RELATION_PAYER ORDER BY SUBQRY1.BILLING_DATE DESC) CUM_BILLING_AMT,
SUBQRY1.DAYNUM,
SUBQRY1.BILLING_DATE
FROM
(
SELECT DISTINCT
 I.TERRITORY_ID AS TERRITORY_ID,
 I.CODE_RELATION_PAYER AS CODE_RELATION_PAYER,
 SUM(TOT_AMOUNT) AS BILLING_AMT,
CAST(CURRENT_TIMESTAMP AS DATE FORMAT 'MM/DD/YYYY') - CAST(I.INVOICE_DATE AS DATE FORMAT 'MM/DD/YYYY' ) AS DAYNUM,
 I.INVOICE_DATE AS BILLING_DATE
FROM
 %TOBI_ODS%.INVOICE  I
WHERE  I.INVOICE_STATUS in ('f','a')
AND    I.INVOICE_DATE <=  CURRENT_DATE 
AND    I.TERRITORY_ID IN 
	   (SELECT TERRITORY_ID FROM %TOBI_ADMIN%.TOBI_JOB_RUN_TERRITORY WHERE JOB_RUN_FLAG='Y' AND REGION_ID =(SELECT DISTINCT REGION_ID FROM %TOBI_ADMIN%.TOBI_JOB_SQL_FILE_PATH WHERE JOB_RUN_FLAG='Y'))
GROUP BY I.TERRITORY_ID,I.CODE_RELATION_PAYER,I.INVOICE_DATE
)SUBQRY1 ;


/* --------------------------------DELETE / INSERT TEMP_WBO_DATA_PAYER SQL END --------------------------------------- */


/* --------------------------------DELETE / INSERT TEMP_WBO_PAYER SQL START --------------------------------------- */

DELETE %TOBI_ODS%.TEMP_WBO_PAYER where TERRITORY_ID IN
(SELECT TERRITORY_ID FROM %TOBI_ADMIN%.TOBI_JOB_RUN_TERRITORY WHERE JOB_RUN_FLAG='Y' AND REGION_ID =(SELECT DISTINCT REGION_ID FROM %TOBI_ADMIN%.TOBI_JOB_SQL_FILE_PATH WHERE JOB_RUN_FLAG='Y'));

INSERT INTO  %TOBI_ODS%.TEMP_WBO_PAYER
(
TERRITORY_ID,
CODE_RELATION_PAYER,
DBO,
WBO
)
SELECT W.TERRITORY_ID AS TERRITORY_ID ,W.CODE_RELATION_PAYER AS CODE_RELATION_PAYER,
--W.CODE_CIRCUIT AS CODE_CIRCUIT,
MIN(DAYNUM) AS DBO , ROUND(MIN(DAYNUM)/7,2) AS WBO
FROM %TOBI_ODS%.TEMP_WBO_DATA_PAYER W
WHERE W.CUM_BILLING_AMT >= ( SELECT I.AR_AMOUNT FROM %TOBI_ODS%.TEMP_INVOICE_DATA_PAYER I WHERE I.TERRITORY_ID = W.TERRITORY_ID
							 AND I.CODE_RELATION_PAYER =  W.CODE_RELATION_PAYER)
AND W.TERRITORY_ID IN 
(SELECT TERRITORY_ID FROM %TOBI_ADMIN%.TOBI_JOB_RUN_TERRITORY WHERE JOB_RUN_FLAG='Y' AND REGION_ID =(SELECT DISTINCT REGION_ID FROM %TOBI_ADMIN%.TOBI_JOB_SQL_FILE_PATH WHERE JOB_RUN_FLAG='Y'))
GROUP BY W.TERRITORY_ID,W.CODE_RELATION_PAYER--,W.CODE_CIRCUIT
;

/* --------------------------------DELETE / INSERT TEMP_WBO_PAYER SQL END --------------------------------------- */

/* --------------------------------UPDATE ACCOUNTS_RECEIVABLE_FCT SQL START ------------------------------------------- */

UPDATE %TOBI_MDM%.ACCOUNTS_RECEIVABLE_FCT
FROM
(
SELECT 
SRC.FK_TERRITORY_DIM_ID AS PK_TERRITORY_DIM_ID,
SRC.PK_PARTY_CINEMA_DIM_ID AS  PK_PARTY_CINEMA_PAYER_DIM_ID,
SRC.PK_TIME_DIM_ID AS PK_TIME_DIM_ID,
0 AS PK_INVOICE_DIM_ID,
0 AS PK_TITLE_DIM_ID,
SRC.PK_PARTY_CIRCUIT_DIM_ID AS FK_PARTY_CIRCUIT,
TO_DATE('01-Jan-1900','DD-Mon-YYYY') AS CURRENT_RUN_DT,
0 AS PK_PAYMENT_DIM_ID,
0 AS PK_PAYMENT_SUBCODE_NK,
0 AS PK_PAYMENT_SUBDETCODE_NK,
0 AS PK_BATCH_ID,
LKUP_ACC_REV.ACC_REV_12MNTHS AS ACC_REV_12MNTHS,
0 AS FK_DISTRIBUTOR_DIM_ID
FROM 
(
SELECT	
PARTY_CINEMA_PAYER_DIM.PK_PARTY_DIM_ID AS PK_PARTY_CINEMA_DIM_ID, 
PARTY_CINEMA_PAYER_DIM.FK_TERRITORY_DIM_ID,
TEMP_WBO_PAYER.DBO, 
TEMP_WBO_PAYER.WBO, 
TIME_DIM.PK_TIME_DIM_ID,
TTT_PAYER.CODE_CIRCUIT, 
TTT_PAYER.CODE_PAYER_GROUP, 
PARTY_CIRCUIT_DIM.PK_PARTY_DIM_ID AS PK_PARTY_CIRCUIT_DIM_ID
FROM %TOBI_MDM%.TIME_DIM, 
%TOBI_ODS%.TEMP_WBO_PAYER, 
%TOBI_MDM%.PARTY_CINEMA_PAYER_DIM,
%TOBI_ODS%.PAYER AS TTT_PAYER,
%TOBI_MDM%.PARTY_CIRCUIT_DIM
WHERE PARTY_CINEMA_PAYER_DIM.FK_TERRITORY_DIM_ID= TEMP_WBO_PAYER.TERRITORY_ID
AND	PARTY_CINEMA_PAYER_DIM.PARTY_CD_NK = TEMP_WBO_PAYER.CODE_RELATION_PAYER
AND	PARTY_CINEMA_PAYER_DIM.FK_TERRITORY_DIM_ID = TTT_PAYER.TERRITORY_ID
AND	PARTY_CINEMA_PAYER_DIM.PARTY_CD_NK = TTT_PAYER.CODE_RELATION_PAYER
AND	PARTY_CIRCUIT_DIM.FK_TERRITORY_DIM_ID = TTT_PAYER.TERRITORY_ID
AND	PARTY_CIRCUIT_DIM.PARTY_CD_NK = TTT_PAYER.CODE_CIRCUIT
AND	TIME_DIM.FULL_DATE = ( SELECT MAX(DATE_ID) FROM	%TOBI_ADMIN%.FDDM_LOAD_SCHEDULE 
					       WHERE REGION_ID = (SELECT DISTINCT REGION_ID FROM %TOBI_ADMIN%.TOBI_JOB_SQL_FILE_PATH WHERE JOB_RUN_FLAG='Y') AND AR_LOAD_STATUS = 'Y' )
AND PARTY_CINEMA_PAYER_DIM.FK_TERRITORY_DIM_ID IN 
(SELECT TERRITORY_ID FROM %TOBI_ADMIN%.TOBI_JOB_RUN_TERRITORY WHERE JOB_RUN_FLAG='Y' AND REGION_ID = (SELECT DISTINCT REGION_ID FROM %TOBI_ADMIN%.TOBI_JOB_SQL_FILE_PATH WHERE JOB_RUN_FLAG='Y'))
) SRC

LEFT JOIN  %TOBI_MDM%.TEMP_ACC_REV_PAYER LKUP_ACC_REV 
ON  LKUP_ACC_REV.TERRITORY_ID = SRC.FK_TERRITORY_DIM_ID 
AND LKUP_ACC_REV.PAYER_DIM_ID = SRC.PK_PARTY_CINEMA_DIM_ID

LEFT JOIN %TOBI_MDM%.ACCOUNTS_RECEIVABLE_FCT TGT
ON  TGT.PK_TERRITORY_DIM_ID = SRC.FK_TERRITORY_DIM_ID
AND TGT.PK_PARTY_CINEMA_PAYER_DIM_ID = SRC.PK_PARTY_CINEMA_DIM_ID
AND TGT.PK_TIME_DIM_ID = SRC.PK_TIME_DIM_ID
AND TGT.PK_INVOICE_DIM_ID=0 AND TGT.PK_TITLE_DIM_ID=0 AND TGT.PK_PAYMENT_DIM_ID=0 AND TGT.PK_PAYMENT_SUBCODE_NK=0 AND TGT.PK_PAYMENT_SUBDETCODE_NK=0 AND TGT.PK_BATCH_ID=0 

WHERE  TGT.PK_TERRITORY_DIM_ID IS NOT NULL AND TGT.PK_PARTY_CINEMA_PAYER_DIM_ID IS NOT NULL AND TGT.PK_TIME_DIM_ID IS NOT NULL
AND TGT.PK_INVOICE_DIM_ID IS NOT NULL AND TGT.PK_TITLE_DIM_ID IS NOT NULL AND TGT.PK_PAYMENT_DIM_ID IS NOT NULL AND TGT.PK_PAYMENT_SUBCODE_NK IS NOT NULL 
AND TGT.PK_PAYMENT_SUBDETCODE_NK IS NOT NULL AND TGT.PK_BATCH_ID IS NOT NULL
) UPDT
SET FK_PARTY_CIRCUIT = UPDT.FK_PARTY_CIRCUIT,
CURRENT_RUN_DT = UPDT.CURRENT_RUN_DT,
ACC_REV_12MNTHS = UPDT.ACC_REV_12MNTHS,
FK_DISTRIBUTOR_DIM_ID = UPDT.FK_DISTRIBUTOR_DIM_ID
WHERE PK_TERRITORY_DIM_ID IN (SELECT TERRITORY_ID FROM %TOBI_ADMIN%.TOBI_JOB_RUN_TERRITORY WHERE JOB_RUN_FLAG='Y' AND REGION_ID = (SELECT DISTINCT REGION_ID FROM %TOBI_ADMIN%.TOBI_JOB_SQL_FILE_PATH WHERE JOB_RUN_FLAG='Y'))

;

/* --------------------------------UPDATE ACCOUNTS_RECEIVABLE_FCT SQL END ------------------------------------------- */


/* --------------------------------INSERT ACCOUNTS_RECEIVABLE_FCT SQL START --------------------------------------- */
 
INSERT INTO %TOBI_MDM%.ACCOUNTS_RECEIVABLE_FCT
(
PK_TERRITORY_DIM_ID,
PK_PARTY_CINEMA_PAYER_DIM_ID,
PK_TIME_DIM_ID,
PK_INVOICE_DIM_ID,
PK_TITLE_DIM_ID,
FK_PARTY_CIRCUIT,
CURRENT_RUN_DT,
PK_PAYMENT_DIM_ID,
PK_PAYMENT_SUBCODE_NK,
PK_PAYMENT_SUBDETCODE_NK,
PK_BATCH_ID,
ACC_REV_12MNTHS,
FK_DISTRIBUTOR_DIM_ID
)
SELECT 
SRC.FK_TERRITORY_DIM_ID AS PK_TERRITORY_DIM_ID,
SRC.PK_PARTY_CINEMA_DIM_ID AS  PK_PARTY_CINEMA_PAYER_DIM_ID,
SRC.PK_TIME_DIM_ID AS PK_TIME_DIM_ID,
0 AS PK_INVOICE_DIM_ID,
0 AS PK_TITLE_DIM_ID,
SRC.PK_PARTY_CIRCUIT_DIM_ID AS FK_PARTY_CIRCUIT,
TO_DATE('01-Jan-1900','DD-Mon-YYYY') AS CURRENT_RUN_DT,
0 AS PK_PAYMENT_DIM_ID,
0 AS PK_PAYMENT_SUBCODE_NK,
0 AS PK_PAYMENT_SUBDETCODE_NK,
0 AS PK_BATCH_ID,
LKUP_ACC_REV.ACC_REV_12MNTHS AS ACC_REV_12MNTHS,
0 AS FK_DISTRIBUTOR_DIM_ID
FROM 
(
SELECT	
PARTY_CINEMA_PAYER_DIM.PK_PARTY_DIM_ID AS PK_PARTY_CINEMA_DIM_ID, 
PARTY_CINEMA_PAYER_DIM.FK_TERRITORY_DIM_ID,
TEMP_WBO_PAYER.DBO, 
TEMP_WBO_PAYER.WBO, 
TIME_DIM.PK_TIME_DIM_ID,
TTT_PAYER.CODE_CIRCUIT, 
TTT_PAYER.CODE_PAYER_GROUP, 
PARTY_CIRCUIT_DIM.PK_PARTY_DIM_ID AS PK_PARTY_CIRCUIT_DIM_ID
FROM %TOBI_MDM%.TIME_DIM, 
%TOBI_ODS%.TEMP_WBO_PAYER, 
%TOBI_MDM%.PARTY_CINEMA_PAYER_DIM,
%TOBI_ODS%.PAYER AS TTT_PAYER,
%TOBI_MDM%.PARTY_CIRCUIT_DIM
WHERE PARTY_CINEMA_PAYER_DIM.FK_TERRITORY_DIM_ID= TEMP_WBO_PAYER.TERRITORY_ID
AND	PARTY_CINEMA_PAYER_DIM.PARTY_CD_NK = TEMP_WBO_PAYER.CODE_RELATION_PAYER
AND	PARTY_CINEMA_PAYER_DIM.FK_TERRITORY_DIM_ID = TTT_PAYER.TERRITORY_ID
AND	PARTY_CINEMA_PAYER_DIM.PARTY_CD_NK = TTT_PAYER.CODE_RELATION_PAYER
AND	PARTY_CIRCUIT_DIM.FK_TERRITORY_DIM_ID = TTT_PAYER.TERRITORY_ID
AND	PARTY_CIRCUIT_DIM.PARTY_CD_NK = TTT_PAYER.CODE_CIRCUIT
AND	TIME_DIM.FULL_DATE = ( SELECT MAX(DATE_ID) FROM	%TOBI_ADMIN%.FDDM_LOAD_SCHEDULE 
					       WHERE REGION_ID = (SELECT DISTINCT REGION_ID FROM %TOBI_ADMIN%.TOBI_JOB_SQL_FILE_PATH WHERE JOB_RUN_FLAG='Y') AND AR_LOAD_STATUS = 'Y' )
AND PARTY_CINEMA_PAYER_DIM.FK_TERRITORY_DIM_ID IN 
(SELECT TERRITORY_ID FROM %TOBI_ADMIN%.TOBI_JOB_RUN_TERRITORY WHERE JOB_RUN_FLAG='Y' AND REGION_ID = (SELECT DISTINCT REGION_ID FROM %TOBI_ADMIN%.TOBI_JOB_SQL_FILE_PATH WHERE JOB_RUN_FLAG='Y'))
) SRC

LEFT JOIN  %TOBI_MDM%.TEMP_ACC_REV_PAYER LKUP_ACC_REV 
ON  LKUP_ACC_REV.TERRITORY_ID = SRC.FK_TERRITORY_DIM_ID 
AND LKUP_ACC_REV.PAYER_DIM_ID = SRC.PK_PARTY_CINEMA_DIM_ID

;
/* --------------------------------INSERT ACCOUNTS_RECEIVABLE_FCT SQL END ------------------------------------------- */
 