name: S3 Sync
on [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Sync to S3
        uses: raulanatol/aws-s3-docker-action@master
        env:
          # AWS_ACCESS_KEY_ID:
          # AWS_SECRET_ACCESS_KEY:
           AWS_REGION: us-west-2
          AWS_BUCKET_NAME: vijaya-test-dev
          SOURCE: Sample_DCX/ .github/DEV/sample.txt
          TARGET:test/
