name: Sync to S3 bucket
on:
  pull_request:
    branches:
      - main 
      - 'DEV'
      
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install awscli
      - run: aws s3 cp sample.txt s3://tobi-etl-dev/source/
        env:
          AWS_ACCESS_KEY_ID: AKIARJZZSGSWHCJCOPM4 
          AWS_SECRET_ACCESS_KEY: xD7zQ+B6Ycn1okIvTTJgDr8rzI26V8SKTwI0lw/K
