# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ QA ]
  pull_request:
    branches: [ QA ]
jobs:
  MERGE_QA:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: sync dev to QA 
        run: git merge DEV
             git commit
 
