name: Upload a folder to S3 DEV

on:
  push:
    branches:
      - main 
      - 'QA'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Copy a folder to s3
      uses: prewk/s3-cp-action@v2
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        source: './Sample_DCX/ .github/MASTER_DATA'
        dest: 's3://vijaya-test-dev2/source/'
        flags: --recursive

