name: Upload a folder to S3 DEV

on:
  push:
    branches:
      - main 
      - 'QA'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Copy a folder to s3
      uses: prewk/s3-cp-action@v2
      with:
        aws_access_key_id:
        aws_secret_access_key: 
        source: 'Sample_DCX/ .github/sample.txt'
        dest: 's3:///source'
        #flags: --recursive
